---
- hosts: 172.31.21.105
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myResult

- name: i want to display myfrist task result
  debug: 
     msg: "{{myResult}}"

- name: install tree
  apt:
    name: git
    state: 
  when: myResult.stderr ==""  

- name: install tree
  apt:
    name: tree
    state: present             
  when: myResult.stderr !=""  