---
- hosts: 172.31.21.105
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      state: present

  - name: install tree
    apt: 
      name: tree
      state: present

  - name: installl wget
    apt: 
      name: wget
      state: present



