---
- hosts: 172.31.21.105
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      state: present
    tags: mygit

  - name: install tree
    apt: 
      name: tree
      stateee: present
    tags: mytree
    ignor_error: yes

  - name: installl wget
    apt: 
      name: wget
      state: present
    tags: mywget



